import {Suspense} from 'react'
import LoadingIndicator from "../../components/loadingIndicator/LoadingIndicator";
import PageContent from "../../components/PageContent/PageContent";
import Link from "next/link";
import Section from "../../components/section/Section";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AccountLayout({ children }) {
    return (
        <Suspense fallback={<LoadingIndicator />}>
            <PageContent>
                <Section>
                    <div className="post-container account-content sidebar-enabled sidebar-left">
                        <div className="sidebar sidebar-left">
                            <h2>Sidebar</h2>
                            <div>
                                <h2>Account Navigation</h2>
                                <ul>
                                    <li>
                                        <Link href="/account/main-menu">Edit Main Menu</Link>
                                    </li>
                                    <li>
                                        <Link href="/account/create-post">Add Post</Link>
                                    </li>
                                    <li>
                                        <Link href="/account/upsert-pinecone">Upsert to pinecone</Link>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="post-content">
                            <h1>Welcome to the Dashboard</h1>
                            {children}
                        </div>
                    </div>
                </Section>
            </PageContent>
        </Suspense>
    );
}