import { Geist, Geist_Mono } from "next/font/google";
import {Suspense} from 'react'
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import PageContent from "../components/PageContent/PageContent";
import LoadingIndicator from "../components/loadingIndicator/LoadingIndicator";
import PageLoader from "./books/PageLoader";
import {Provider} from "react-redux";
import {store} from "@/store/index";
import ClientProviders from "../components/ClientProviders/ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ClientProviders>
        <html lang="en">
          <body>
              <Header />
              <PageContent>
                {children}
              </PageContent>
              <Footer />
          </body>
        </html>
    </ClientProviders>
  );
}
