import {Suspense} from 'react'
import "../globals.css";
import PageContent from "../../components/PageContent/PageContent";
import LoadingIndicator from "../../components/loadingIndicator/LoadingIndicator";
import PostsFilter from "../../components/posts-filter/PostsFilter";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function BooksLayout({ children }) {
    return (
        <Suspense fallback={<LoadingIndicator />}>
            <PageContent>
                {children}
            </PageContent>
        </Suspense>
    );
}
